name: Build and Deploy price_percentage App to GitHub Pages

on:
  push:
    branches: [ "gtrx" ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Deploy
      run: |
        git config --global user.name 'sturdoodle'
        git config --global user.email '113435474+sturdoodle@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy